server:
port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: auth-server
#          uri: lb://auth-server
#          predicates:
#            - Path=/auth/**
#        - id: contact
#            uri: lb://contact
#            predicates:
#              - Path=/contact/**
#        - id: summary
#            uri: lb://summary
#            predicates:
#              - Path=/summary/**
#        - id: timesheet
#            uri: lb://timesheet
#            predicates:
#              - Path=/timesheet/**
  spring:
    cloud:
      gateway:
        routes:
          - id: auth-server
            uri: lb://auth-server
            predicates:
              - Path=/auth/**
          - id: contact
            uri: lb://contact
            predicates:
              - Path=/contact/**
          - id: summary
            uri: lb://summary
            predicates:
              - Path=/summary/**
          - id: timesheet
            uri: lb://timesheet
            predicates:
              - Path=/timesheet/**