spring:
  application:
    name: timesheet
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: project-3
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true